SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `acesso` (
  `id` int(11) NOT NULL,
  `login` varchar(60) NOT NULL,
  `senha` varchar(255) NOT NULL,
  `cpf` varchar(14) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `livros` (
  `id` int(11) NOT NULL,
  `titulo` varchar(200) NOT NULL,
  `autor` varchar(120) NOT NULL,
  `preco` varchar(20) NOT NULL,
  `categoria` varchar(50) NOT NULL,
  `destaque` tinyint(1) DEFAULT 0,
  `imagem` varchar(150) DEFAULT NULL,
  `sinopse` text DEFAULT NULL,
  `editora` varchar(100) DEFAULT NULL,
  `publicacao` varchar(20) DEFAULT NULL,
  `edicao` varchar(80) DEFAULT NULL,
  `idioma` varchar(50) DEFAULT NULL,
  `paginas` varchar(20) DEFAULT NULL,
  `peso` varchar(20) DEFAULT NULL,
  `idade` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `livros` (`id`, `titulo`, `autor`, `preco`, `categoria`, `destaque`, `imagem`, `sinopse`, `editora`, `publicacao`, `edicao`, `idioma`, `paginas`, `peso`, `idade`) VALUES
(1, 'Orgulho e Preconceito', 'Jane Austen', 'R$ 200,00', 'Romance', 0, '1.png', 'A jovem Elizabeth Bennet navega questões de casamento, moralidade e felicidade na Inglaterra do século XIX, em um dos maiores romances da literatura inglesa.', 'Penguin Companhia', '1813', '1ª edição especial', 'Português', '424', '420g', '14+'),
(2, 'Como Eu Era Antes de Você', 'Jojo Moyes', 'R$ 39,90', 'Romance', 1, '2.jpg', 'Louisa Clark, uma jovem otimista, se torna cuidadora de Will Traynor, um homem tetraplégico amargo mas brilhante. Uma história de amor transformadora.', 'Intrínseca', '2012', '1ª edição', 'Português', '384', '380g', '16+'),
(3, 'A Culpa é das Estrelas', 'Jhon Green', 'R$ 39,90', 'Romance', 1, '3.jpg', 'Hazel e Augustus são dois adolescentes com câncer que se conhecem em um grupo de apoio. Uma história de amor, vida e morte que comove o mundo inteiro.', 'Intrínseca', '2012', '1ª edição', 'Português', '288', '280g', '14+'),
(4, 'Diário de uma Paixão', 'Nicholas Sparks', 'R$ 34,90', 'Romance', 0, '4.jpg', 'Noah Calhoun e Allie Hamilton vivem um romance intenso separado pela guerra e pela distância social, numa história de amor eterno e inesquecível.', 'Arqueiro', '1996', '1ª edição', 'Português', '208', '200g', '14+'),
(5, 'Eleanor & Park', 'Rainbow Rowell', 'R$ 38,90', 'Romance', 0, '5.jpg', 'Eleanor e Park se encontram no ônibus escolar e formam uma conexão improvávelmas poderosa, em um romance sobre primeiros amores e ser diferente.', 'Galera Record', '2013', '1ª edição', 'Português', '320', '300g', '14+'),
(6, 'Simplesmente Acontece', 'Cecelia Ahern', 'R$ 42,90', 'Romance', 1, '6.jpg', 'Uma mulher descobre cartas misteriosas que mudam sua vida, numa narrativa mágica e encantadora sobre amor, destino e conexões inesperadas.', 'Sextante', '2004', '1ª edição', 'Português', '320', '310g', '16+'),
(7, 'O Morro dos Ventos Uivantes', 'Emily Brontë', 'R$ 32,90', 'Romance', 0, '7.jpg', 'Heathcliff e Catherine protagonizam um dos amores mais apaixonados e destrutivos da literatura, numa saga de obsessão e vingança nos páramos ingleses.', 'Martin Claret', '1847', '1ª edição revisada', 'Português', '384', '370g', '16+'),
(8, 'P.S. Eu Te Amo', 'Cecelia Ahern', 'R$ 36,90', 'Romance', 0, '8.jpg', 'Holly recebe cartas pósumas do marido que faleceu, cada uma guiando-a a redescobrir a vida e o amor. Uma história de perda, cura e recomeço.', 'Sextante', '2004', '1ª edição', 'Português', '310', '300g', '16+'),
(9, 'O Clube P.S. Eu Te Amo', 'Cecelia Ahern', 'R$ 36,90', 'Romance', 0, '9.jpg', 'Continuação emocionante da saga P.S. Eu Te Amo, onde Holly e suas amigas embarcam em novas jornadas de amor e autodescoberta.', 'Sextante', '2011', '1ª edição', 'Português', '320', '300g', '16+'),
(10, 'Anna e o Beijo Francês', 'Stephanie Perkins', 'R$ 37,90', 'Romance', 0, '10.jpg', 'Anna vai passar o último ano do ensino médio em Paris e encontra o charmoso Étienne St. Clair. Um romance doce ambientado na cidade do amor.', 'Galera Record', '2010', '1ª edição', 'Português', '416', '390g', '14+'),
(11, 'Um Dia', 'David Nicholls', 'R$ 36,90', 'Romance', 0, '11.jpg', 'Dexter e Emma se encontram no dia da formatura e se tornam amigos inseparáveis. O livro acompanha o mesmo dia - 15 de julho - ao longo de 20 anos.', 'Companhia das Letras', '2009', '1ª edição', 'Português', '448', '420g', '16+'),
(12, 'Amor & Gelato', 'Jenna Evans Welch', 'R$ 38,90', 'Romance', 0, '12.jpg', 'Lina vai para a Itália após a morte da mãe e descobre um diário e uma história de amor secreta que transforma completamente sua visão da vida.', 'Galera Record', '2017', '1ª edição', 'Português', '400', '370g', '14+'),
(13, 'Teto Para Dois', 'Beth O\'Lears', 'R$ 42,90', 'Romance', 1, '13.jpg', 'Dois estranhos dividem um apartamento por necessidade e acabam descobrindo que o amor pode surgir nos lugares mais improváveis.', 'Arqueiro', '2019', '1ª edição', 'Português', '352', '330g', '16+'),
(14, 'Leitura de Verão', 'Emily Henry', 'R$ 44,90', 'Romance', 0, '14.jpg', 'A escritora Harriet leva o verão numa cidade litorânea e descobre romances inesperados, segredos da família e o significado de ler e amar.', 'Intrínseca', '2022', '1ª edição', 'Português', '384', '360g', '16+'),
(15, 'É Assim Que Acaba', 'Collen Hoover', 'R$ 44,90', 'Romance', 0, '15.jpg', 'Uma história intensa e poderosa sobre um relacionamento abusivo e a coragem de se libertar. Colleen Hoover no seu melhor, mais sombrio e mais real.', 'Galera Record', '2016', '1ª edição', 'Português', '320', '300g', '18+'),
(16, 'É Assim Que Começa', 'Colleen Hoover', 'R$ 42,90', 'Romance', 0, '16.jpg', 'Prequel de É Assim Que Acaba, contando como Lily e Ryle se conheceram. Uma história de amor apaixonante que explora os sinais de alerta num relacionamento.', 'Galera Record', '2017', '1ª edição', 'Português', '320', '300g', '18+'),
(17, 'Amor(es) Verdadeiro(s)', 'Taylor Jenkins Reid', 'R$ 40,90', 'Romance', 0, '17.jpg', 'Uma mulher olha para trás e para frente no tempo para entender seus amores, suas escolhas e a pergunta: existe uma alma gêmea verdadeira?', 'Intrínseca', '2019', '1ª edição', 'Português', '352', '330g', '16+'),
(18, 'Corte de Espinhos e Rosas', 'Sarah J. Maas', 'R$ 49,90', 'Romance Fantasia', 1, '18.jpg', 'Feyre caça para sobreviver e acaba sendo capturada por uma criatura do mundo feérico. Uma história épica de amor proibido entre mundos.', 'Galera Record', '2015', '1ª edição', 'Português', '448', '430g', '16+'),
(19, 'A Lâmina Assassina', 'Sarah J. Maas', 'R$ 47,90', 'Romance Fantasia', 0, '19.jpg', 'A jovem assassina Celaena Sardothien deve participar de uma competição mortal para ganhar a liberdade, enquanto enfrenta poderes sobrenaturais.', 'Galera Record', '2012', '1ª edição', 'Português', '432', '410g', '16+'),
(20, 'A Rainha Vermelha', 'Victoria Aveyard', 'R$ 44,90', 'Romance Fantasia', 0, '20.jpg', 'Num mundo dividido entre Sangue de Prata e Sangue de Vermelho, Mare Barrow descobre poderes impossíveis e enfrenta uma revolução que pode destruir tudo.', 'Galera Record', '2015', '1ª edição', 'Português', '400', '380g', '14+'),
(21, 'Crepúsculo', 'Stephenie Meyer', 'R$ 39,90', 'Romance Fantasia', 0, '21.jpg', 'Bella Swan muda para Forks e se apaixona pelo misterioso Edward Cullen. Uma saga vampírica que conquistou leitores de todo o mundo.', 'Intrínseca', '2005', '1ª edição', 'Português', '432', '400g', '14+'),
(22, 'O Príncipe Cruel', 'Holly Black', 'R$ 46,90', 'Romance Fantasia', 1, '22.jpg', 'Jude é levada ao mundo feérico e precisa sobreviver às intrigas perigosas da corte. Um romance sombrio de poder, traição e amor inesperado.', 'Galera Record', '2018', '1ª edição', 'Português', '384', '360g', '16+'),
(23, 'Sombra e Ossos', 'Leigh Bardugo', 'R$ 48,90', 'Romance Fantasia', 0, '23.jpg', 'Alina descobre poderes de Invocadora de Luz e é levada para o exército do Grisha, onde o misterioso Darkling desperta algo que ela não esperava.', 'Galera Record', '2012', '1ª edição', 'Português', '368', '350g', '14+'),
(24, 'Caraval', 'Stephanie Garber', 'R$ 45,90', 'Romance Fantasia', 0, '24.jpg', 'Scarlett Dragna ganha o ingresso para o Caraval, um jogo lendário onde tudo pode ser real ou ilusão - inclusive o amor e a morte.', 'Galera Record', '2017', '1ª edição', 'Português', '416', '390g', '14+'),
(25, 'A Seleção', 'Kiera Cass', 'R$ 40,90', 'Romance Fantasia', 0, '25.jpg', 'Em plena competição para ser a esposa do príncipe, America Singer não quer participar - mas o Príncipe Maxon pode mudar tudo.', 'Galera Record', '2012', '1ª edição', 'Português', '336', '320g', '14+'),
(26, 'A Ponte Entre Reinos', 'Danielle L. Jensen', 'R$ 43,90', 'Romance Fantasia', 0, '26.jpg', 'Uma jovem é oferecida em casamento a um príncipe do mundo sobrenatural e descobre que fronteiras entre reinos guardam segredos e amores perigosos.', 'Galera Record', '2014', '1ª edição', 'Português', '368', '340g', '16+'),
(27, 'O Beijo Traiçoeiro', 'Erin Beaty', 'R$ 44,90', 'Romance Fantasia', 0, '27.jpg', 'Uma espiã disfarçada de dama da corte enfrenta intrigas políticas e um amor proibido numa história de aventura, segredos e traição.', 'Galera Record', '2016', '1ª edição', 'Português', '352', '330g', '14+'),
(28, 'Quarta Asa', 'Rebecca Yarros', 'R$ 54,90', 'Romance Fantasia', 1, '28.jpg', 'Violet Sorrengail entra na escola de pilotos de dragão e descobre que sobreviver é apenas o começo - o amor e a guerra são ainda mais implacáveis.', 'Galera Record', '2023', '1ª edição', 'Português', '528', '510g', '16+'),
(29, 'De Sangue e Cinzas', 'Jennifer L. Armentrout', 'R$ 49,90', 'Romance Fantasia', 0, '29.jpg', 'Poppy vive protegida por regras rígidas do reino, mas quando o Guarda Hawke aparece, ela descobre segredos que mudam tudo o que acreditava.', 'Galera Record', '2020', '1ª edição', 'Português', '496', '470g', '16+'),
(30, 'O Feitiço dos Espinhos', 'Margaret Rogerson', 'R$ 46,90', 'Romance Fantasia', 0, '30.png', 'Isobel é uma bordadeira lançada no mundo das fadas por seu poder único, onde o amor e a magia se entrelaçam em uma tapeçaria de consequências.', 'Galera Record', '2018', '1ª edição', 'Português', '320', '300g', '14+'),
(31, 'Gild', 'Raven Kennedy', 'R$ 47,90', 'Romance Fantasia', 0, '31.jpg', 'Filha de Midas, Auren é coberta de ouro e mantida em uma gaiola dourada. Uma história sobre liberdade, poder e amor em um mundo de fadas.', 'Galera Record', '2020', '1ª edição', 'Português', '432', '410g', '16+'),
(32, 'Estilhaça-me', 'Tahereh Mafi', 'R$ 44,90', 'Romance Fantasia', 0, '32.jpg', 'Juliette possui um toque letal e foi encarcerada por isso. Quando o misterioso Warner a recruta, ela descobre que seu poder é uma arma - e talvez uma dádiva.', 'Galera Record', '2011', '1ª edição', 'Português', '352', '330g', '14+'),
(33, 'Dinastia de Ladrões', 'Marry E. Pearson', 'R$ 49,90', 'Romance Fantasia', 0, '33.jpg', 'Uma ladra de memórias e um príncipe exilado precisam trabalhar juntos para recuperar o que foi roubado, descobrindo que o passado esconde mais segredos do que imaginam.', 'Galera Record', '2018', '1ª edição', 'Português', '480', '450g', '14+'),
(34, 'Desejo (Série Crave)', 'Tracy Wolff', 'R$ 45,90', 'Romance Fantasia', 0, '34.jpg', 'Bryn chega à Vamp U sem saber que está no meio de uma guerra sobrenatural. Romance intenso e cheio de mistério com vampiros, dragões e feras.', 'Intrínseca', '2020', '1ª edição', 'Português', '464', '440g', '16+'),
(35, 'Contos de Grimm', 'Irmãos Grimm', 'R$ 29,90', 'Contos', 0, '36.jpg', 'A coletânea mais famosa dos irmãos Grimm reunindo contos clássicos como Chapeuzinho Vermelho, Rapunzel e Branca de Neve nas versões originais mais sombrias.', 'Zahar', '1812', 'Edição comentada', 'Português', '832', '780g', '12+'),
(36, 'Contos de Fadas', 'Vários Autores', 'R$ 27,90', 'Contos', 0, '35.jpg', 'Seleção de contos de fadas de diversas tradições europeias, reunindo histórias de magia, amor e aventura que atravessam gerações.', 'Zahar', '2002', '1ª edição', 'Português', '320', '300g', '10+'),
(37, 'Ficções', 'Jorge Luis Borges', 'R$ 38,90', 'Contos', 1, '37.jpg', 'Uma das obras mais importantes da literatura latino-americana, reunindo 17 contos que exploram labirintos, infinitos e realidades alternativas com maestria única.', 'Companhia das Letras', '1944', 'Edição especial', 'Português', '128', '150g', '16+'),
(38, 'Primeiras Estórias', 'João Guimarães Rosa', 'R$ 36,90', 'Contos', 0, '38.jpg', '21 contos do mestre da prosa brasileira, explorando o sertão, a condição humana e o universo mítico do interior do Brasil com linguagem inovadora.', 'Nova Fronteira', '1962', '4ª edição', 'Português', '240', '230g', '16+'),
(39, 'Laços de Família', 'Clarice Lispector', 'R$ 34,90', 'Contos', 0, '39.jpg', 'Clarice Lispector revela o cotidiano feminino em 13 contos marcados por crises existenciais, epifanias e uma prosa de rara intensidade poética.', 'Rocco', '1960', '3ª edição', 'Português', '176', '170g', '16+'),
(40, 'Contos Novos', 'Mário de Andrade', 'R$ 30,90', 'Contos', 0, '40.jpg', 'Coletânea de contos do autor modernista brasileiro, explorando personagens populares, folclore e a cidade de São Paulo com humor e crítica social.', 'Livraria Martins Editora', '1947', '2ª edição', 'Português', '200', '190g', '14+'),
(41, 'Edgar Allan Poe - Vol. 1', 'Edgar Allan Poe', 'R$ 35,90', 'Contos', 0, '41.jpg', 'Volume 1 da obra completa de Poe, reunindo seus melhores contos de terror e mistério, incluindo O Coração Delator e A Queda da Casa de Usher.', 'Zahar', '1843', 'Edição bilíngue', 'Português/Inglês', '320', '300g', '14+'),
(42, 'Histórias Extraordinárias', 'Edgar Allan Poe', 'R$ 33,90', 'Contos', 0, '42.jpg', 'Antologia com os contos mais extraordinários de Poe, mestre do terror psicológico, incluindo O Poço e o Pêndulo e O Escaravelho de Ouro.', 'Martin Claret', '1840', '2ª edição', 'Português', '304', '290g', '14+'),
(43, 'O Aleph', 'Jorge Luis Borges', 'R$ 37,90', 'Contos', 0, '43.jpg', '17 contos que exploram o infinito, a identidade e o tempo em construções narrativas impossíveis que definiram a literatura fantástica do século XX.', 'Companhia das Letras', '1949', 'Edição especial', 'Português', '208', '200g', '16+'),
(44, 'Doze Contos Peregrinos', 'Gabriel García Márquez', 'R$ 38,90', 'Contos', 0, '44.jpg', '12 contos escritos ao longo de 18 anos, reunindo personagens europeus que vivem situações extraordinárias com a magia realista característica de García Márquez.', 'Record', '1992', '1ª edição', 'Português', '192', '185g', '16+'),
(45, 'Antes que o Café Esfrie', 'Toshikazu Kawaguchi', 'R$ 39,90', 'Contos', 1, '45.jpg', 'Num café de Tóquio, uma fenda no tempo permite visitar o passado. Quatro histórias de amor, perda e esperança que tocam profundamente o coração.', 'Intrínseca', '2015', '1ª edição', 'Português', '224', '215g', '14+'),
(46, 'Nove Histórias', 'J.D. Salinger', 'R$ 33,90', 'Contos', 0, '46.jpg', 'Nove histórias brilhantes e perturbadoras do autor de O Apanhador no Campo de Centeio, explorando personagens à beira do colapso emocional.', 'Editora do Autor', '1953', '2ª edição', 'Português', '208', '200g', '16+'),
(47, 'Felicidade Clandestina', 'Clarice Lispector', 'R$ 32,90', 'Contos', 0, '47.jpg', 'Clarice Lispector revela o prazer da leitura e o desejo em contos que exploram a infância, a feminilidade e o cotidiano com sensibilidade única.', 'Rocco', '1971', '3ª edição', 'Português', '112', '120g', '16+'),
(48, 'O Rei de Amarelo', 'Robert W. Chambers', 'R$ 36,90', 'Contos', 0, '48.jpg', 'Contos interligados que formam um mito sobre o Rei de Amarelo, peça teatral que enlouquece quem a lê. Obra seminal do horror sobrenatural americano.', 'Darkside Books', '1895', '1ª edição brasileira', 'Português', '224', '215g', '16+'),
(49, 'Manual da Faxineira', 'Lucia Berlin', 'R$ 42,90', 'Contos', 0, '49.jpg', 'Contos autobiográficos de Lucia Berlin sobre mulheres que trabalham como faxineiras, enfermeiras e telefonistas - vida real com prosa perfeccionista.', 'Companhia das Letras', '2015', '1ª edição', 'Português', '400', '380g', '16+'),
(50, 'Histórias de Amor', 'Rubem Fonseca', 'R$ 35,90', 'Contos', 0, '50.jpg', 'Rubem Fonseca explora o amor, o desejo e a violência urbana em contos que revelam o lado mais cru e apaixonado da natureza humana.', 'Companhia das Letras', '1997', '2ª edição', 'Português', '208', '200g', '18+'),
(51, 'Em Todos os Sentidos', 'Camila Antunes', 'R$ 38,90', 'Ficção Cristã', 1, '67.jpg', 'Uma jovem cristã navega o amor, a fé e os limites em um romance que equilibra emoção e valores bíblicos com personagens cativantes.', 'Chara', '2021', '1ª edição', 'Português', '280', '265g', '14+'),
(52, 'Os Clãs da Lua', 'Babi A. Sette', 'R$ 38,90', 'Ficção Cristã', 0, '66.jpg', 'Em um mundo de clãs e luas, jovens enfrentam escolhas de fé, amor e pertencimento numa narrativa fantástica de inspiração cristã.', 'Chara', '2020', '1ª edição', 'Português', '304', '290g', '14+'),
(53, 'As Andorinhas de um continente em chamas', 'Gabriela Fernandes', 'R$ 36,90', 'Ficção Cristã', 0, '65.jpg', 'Numa Europa em chamas, jovens andorinhas são símbolos de esperança e resistência. Fé, coragem e amor diante da perseguição.', 'Chara', '2019', '1ª edição', 'Português', '288', '275g', '14+'),
(54, 'Os Pardais do Velho Mundo', 'Gabriela Fernandes', 'R$ 36,90', 'Ficção Cristã', 0, '64.jpg', 'Continuação da saga das Andorinhas, onde os personagens enfrentam provações maiores e descobrem que a fé é o elo que une o velho e o novo mundo.', 'Chara', '2020', '1ª edição', 'Português', '288', '275g', '14+'),
(55, 'Encarando a Verdade', 'Thamires Marinho', 'R$ 35,90', 'Ficção Cristã', 0, '63.jpg', 'Uma jovem que evita confrontos aprende sobre honestidade, coragem e o amor que transforma quando é obrigada a encarar a verdade sobre si mesma.', 'Chara', '2021', '1ª edição', 'Português', '256', '245g', '14+'),
(56, 'Deixa Nevar', 'Camila Antunes', 'R$ 35,90', 'Ficção Cristã', 0, '62.jpg', 'Numa cidade coberta de neve, dois jovens com passados difíceis descobrem que deixar nevar significa também deixar Deus agir no coração.', 'Chara', '2022', '1ª edição', 'Português', '272', '260g', '14+'),
(57, 'A Escolha do Verão', 'Sara Gusella', 'R$ 35,90', 'Ficção Cristã', 0, '61.jpg', 'Um verão, uma escolha e um amor inesperado transformam a vida de uma jovem que aprende que o plano de Deus é sempre melhor que o seu.', 'Chara', '2021', '1ª edição', 'Português', '264', '250g', '14+'),
(58, 'A Pedra e o Dragão', 'Kathryn Butler', 'R$ 39,90', 'Ficção Cristã', 0, '60.jpg', 'Ambientado na Escócia medieval, um médico cristão enfrenta uma ameaça sobrenatural e descobre que a verdadeira batalha é espiritual.', 'Vida', '2020', '1ª edição', 'Português', '320', '305g', '14+'),
(59, 'Esposa Sob Medida', 'Noemi Nicoletti', 'R$ 37,90', 'Ficção Cristã', 0, '59.jpg', 'Valentina aceita um casamento arranjado sem esperar que o contrato traga amor de verdade. Uma história sobre graça, perdão e redenção.', 'Chara', '2021', '1ª edição', 'Português', '288', '275g', '14+'),
(60, 'Círculos não são infinitos', 'Vitória Souza', 'R$ 36,90', 'Ficção Cristã', 0, '58.jpg', 'Vitória Souza escreve sobre amizade, fé e cura emocional numa história que mostra que os círculos de dor têm início, mas também podem ter fim.', 'Chara', '2022', '1ª edição', 'Português', '256', '245g', '14+'),
(61, 'Aurora', 'Vitória Souza', 'R$ 36,90', 'Ficção Cristã', 0, '57.jpg', 'Aurora é uma jovem que busca sua identidade em meio à dor e ao passado. Uma história luminosa de fé e restauração.', 'Chara', '2023', '1ª edição', 'Português', '272', '260g', '14+'),
(62, 'Grama de Vidro', 'Débora Ciampi Eller', 'R$ 35,90', 'Ficção Cristã', 0, '56.jpg', 'Uma jovem descobre que as aparências enganam - inclusive as suas - numa história cristã sobre aceitação, identidade e amor verdadeiro.', 'Chara', '2022', '1ª edição', 'Português', '264', '250g', '14+'),
(63, 'De Repente Ester', 'Kell Carvalho', 'R$ 36,90', 'Ficção Cristã', 0, '55.jpg', 'Ester desperta em um mundo que não reconhece, mas descobre que Deus já preparou o caminho. Uma história de propósito e fé.', 'Chara', '2021', '1ª edição', 'Português', '272', '260g', '14+'),
(64, 'Cidades Pequenas Não Guardam Segredos', 'Kézia Garcia', 'R$ 37,90', 'Ficção Cristã', 0, '54.jpg', 'Numa pequena cidade do interior, segredos do passado emergem e testam a fé e os relacionamentos de seus moradores.', 'Chara', '2022', '1ª edição', 'Português', '280', '265g', '14+'),
(65, 'Sons de Ferrugem e Ecos de Borboleta', 'Noemi Nicoletti', 'R$ 37,90', 'Ficção Cristã', 0, '53.jpg', 'Uma história sobre perdas profundas e a beleza inesperada que nasce delas, com a fé como fio condutor entre sons de ferrugem e asas de borboleta.', 'Chara', '2021', '1ª edição', 'Português', '256', '245g', '14+'),
(66, 'Se pudesse contar as Estrelas', 'Becca Mackenzie', 'R$ 38,90', 'Ficção Cristã', 0, '52.jpg', 'Primeiro volume da duologia de Becca Mackenzie, onde uma jovem cristã enfrenta escolhas impossíveis sob um céu estrelado e cheio de promessas.', 'Chara', '2020', '1ª edição', 'Português', '288', '275g', '14+'),
(67, 'Se pudesse ver as Estrelas', 'Becca Mackenzie', 'R$ 38,90', 'Ficção Cristã', 0, '51.jpg', 'Conclusão da duologia, onde fé e amor se entrelaçam numa jornada de autodescoberta sob o mesmo céu de estrelas que guiou tudo desde o início.', 'Chara', '2021', '1ª edição', 'Português', '296', '280g', '14+'),
(68, 'Duna', 'Frank Herbert', 'R$ 54,90', 'Ficção Científica', 1, '68.jpg', 'No planeta Arrakis, único lugar onde se produz a especiaria mais valiosa do universo, Paul Atreides enfrenta traição, guerra e o destino de uma galáxia.', 'Aleph', '1965', 'Edição especial', 'Português', '688', '650g', '16+'),
(69, 'Fundação', 'Isaac Asimov', 'R$ 48,90', 'Ficção Científica', 0, '69.jpg', 'Hari Seldon desenvolve a psicohistória para prever o colapso da civilização galáctica e cria a Fundação para encurtar a era das trevas.', 'Aleph', '1951', 'Edição especial', 'Português', '320', '305g', '14+'),
(70, '1984', 'George Orwell', 'R$ 38,90', 'Ficção Científica', 0, '70.png', 'Na Inglaterra totalitária de 1984, Winston Smith desafia o Grande Irmão num romance profético sobre vigilância, controle e a resistência da mente humana.', 'Companhia das Letras', '1949', 'Edição especial', 'Português', '416', '390g', '16+'),
(71, 'Admirável Mundo Novo', 'Aldous Huxley', 'R$ 39,90', 'Ficção Científica', 0, '71.jpg', 'Huxley imagina um futuro onde todos são geneticamente fabricados e condicionados para a felicidade. Uma distopia brilhante sobre liberdade e consumo.', 'Globo', '1932', '3ª edição', 'Português', '336', '320g', '16+'),
(72, 'O Guia do Mochileiro das Galáxias', 'Douglas Adams', 'R$ 42,90', 'Ficção Científica', 0, '72.jpg', 'Arthur Dent sobrevive à destruição da Terra e embarca numa viagem galáctica absurda e hilária. A comédia científica mais amada de todos os tempos.', 'Arqueiro', '1979', 'Edição definitiva', 'Português', '240', '230g', '14+'),
(73, 'Neuromancer', 'William Gibson', 'R$ 44,90', 'Ficção Científica', 0, '73.jpg', 'No futuro cyberpunk de Chiba, Case é um ex-hacker contratado para uma missão impossível. O romance que definiu o gênero cyberpunk.', 'Aleph', '1984', 'Edição comemorativa', 'Português', '304', '290g', '16+'),
(74, 'Eu, Robô', 'Isaac Asimov', 'R$ 40,90', 'Ficção Científica', 0, '74.jpg', 'Asimov reúne histórias que exploram as Três Leis da Robótica e as implicações filosóficas de criar vida artificial. Clássico absoluto da FC.', 'Aleph', '1950', 'Edição especial', 'Português', '256', '245g', '14+'),
(75, 'Jogos Vorazes', 'Suzanne Collins', 'R$ 42,90', 'Ficção Científica', 0, '75.jpg', 'Katniss Everdeen é selecionada para os Jogos Vorazes, onde jovens combatem até a morte. Uma distopia emocionante sobre poder, rebeldia e sobrevivência.', 'Rocco', '2008', '1ª edição', 'Português', '400', '380g', '12+'),
(76, 'Fahrenheit 451', 'Ray Bradbury', 'R$ 36,90', 'Ficção Científica', 0, '76.jpg', 'No futuro, livros são proibidos e queimados por bombeiros. Guy Montag questiona a ordem ao encontrar uma jovem que ainda valoriza o conhecimento.', 'Globo', '1953', 'Edição especial', 'Português', '256', '245g', '14+'),
(77, 'Matéria Escura', 'Blake Crouch', 'R$ 46,90', 'Ficção Científica', 1, '77.jpg', 'Jason Dessen é sequestrado e acorda num mundo onde fez escolhas diferentes. Um thriller de ficção científica sobre multiverse e identidade.', 'Intrínseca', '2016', '1ª edição', 'Português', '384', '360g', '16+'),
(78, 'O Problema dos Três Corpos', 'Cixin Liu', 'R$ 52,90', 'Ficção Científica', 0, '78.jpg', 'Ye Wenjie recebe um sinal alienígena e muda o destino da humanidade. Épico de ficção científica sobre primeiro contato e a natureza da civilização.', 'Três Estrelas', '2006', '1ª edição brasileira', 'Português', '432', '410g', '16+'),
(79, 'Perdido em Marte', 'Andy Weir', 'R$ 44,90', 'Ficção Científica', 0, '79.jpg', 'O astronauta Mark Watney fica sozinho em Marte e usa ciência, humor e engenhosidade para sobreviver. Thriler científico irresistível.', 'Intrínseca', '2011', '1ª edição', 'Português', '384', '360g', '14+'),
(80, 'Devoradores de Estrelas', 'Andy Weir', 'R$ 39,90', 'Ficção Científica', 1, '80.jpg', 'Uma missão espacial descobre algo extraordinário nos confins do sistema solar. Andy Weir combina ciência precisa com aventura de ritmo acelerado.', 'Intrínseca', '2021', '1ª edição', 'Português', '496', '470g', '14+'),
(81, 'Carbono Alterado', 'Richard Morgan', 'R$ 47,90', 'Ficção Científica', 0, '81.jpg', 'No futuro em que a consciência pode ser transferida entre corpos, Takeshi Kovacs investiga um crime impossível. Noir cyberpunk de alta voltagem.', 'Aleph', '2002', '1ª edição brasileira', 'Português', '528', '500g', '18+'),
(82, 'Blade Runner: Androides Sonham com Ovelhas Elétricas?', 'Philip K. Dick', 'R$ 42,90', 'Ficção Científica', 0, '82.jpg', 'Rick Deckard é um caçador de recompensas que elimina androides na Terra pós-apocalíptica. A obra que originou o filme Blade Runner.', 'Aleph', '1968', 'Edição especial', 'Português', '240', '230g', '16+'),
(83, 'A Longa Viagem a um Pequeno Planeta Hostil', 'Becky Chambers', 'R$ 45,90', 'Ficção Científica', 0, '83.jpg', 'A tripulação da nave Wayfarer viaja pelo espaço sem missão urgente - e essa simplicidade revela muito sobre coexistência, identidade e humanidade.', 'Arqueiro', '2014', '1ª edição', 'Português', '352', '335g', '14+'),
(84, 'Garota Exemplar', 'Gillian Flynn', 'R$ 43,90', 'Suspense', 1, '84.jpg', 'Nick Dunne acorda no dia do aniversário de casamento com a esposa desaparecida. Um thriller psicológico sobre mentiras, mídia e casamento tóxico.', 'Intrínseca', '2012', '1ª edição', 'Português', '480', '450g', '18+'),
(85, 'O Código Da Vinci', 'Dan Brown', 'R$ 39,90', 'Suspense', 0, '85.jpg', 'Robert Langdon decodifica pistas deixadas por um assassino dentro do Louvre, revelando um segredo que a Igreja guarda há séculos.', 'Sextante', '2003', 'Edição especial', 'Português', '592', '560g', '16+'),
(86, 'A Garota no Trem', 'Paula Hawkins', 'R$ 41,90', 'Suspense', 0, '86.jpg', 'Rachel toma o mesmo trem todo dia e testemunha algo perturbador. Um thriller sombrio sobre memória, obsessão e o que realmente acontece por trás das janelas.', 'Intrínseca', '2015', '1ª edição', 'Português', '400', '380g', '16+'),
(87, 'O Silêncio dos Inocentes', 'Thomas Harris', 'R$ 40,90', 'Suspense', 0, '87.jpg', 'O Dr. Hannibal Lecter ajuda a agente Clarice Starling a rastrear um serial killer. O thriller psicológico mais tenso e sofisticado da literatura.', 'Bertrand Brasil', '1988', '2ª edição', 'Português', '384', '360g', '18+'),
(88, 'Verity', 'Colleen Hoover', 'R$ 46,90', 'Suspense', 1, '88.jpg', 'Lowen Ashleigh descobre o diário perturbador de Verity Crawford e precisa decidir se o que leu é confissão ou ficção. Thriller de Colleen Hoover no limite.', 'Galera Record', '2018', '1ª edição', 'Português', '336', '320g', '18+'),
(89, 'A Paciente Silenciosa', 'Alex Michaelides', 'R$ 44,90', 'Suspense', 0, '89.jpg', 'Alicia Berenson atirou no marido e nunca mais falou. Anos depois, o terapeuta Theo Faber é obrigado a desvendar por que. Reviravoltas até o fim.', 'Arqueiro', '2019', '1ª edição', 'Português', '352', '335g', '16+'),
(90, 'Antes de Dormir', 'S.J. Watson', 'R$ 38,90', 'Suspense', 0, '90.jpg', 'Christine acorda sem memórias e a cada dia escreve num diário o que descobre. Mas o que é real? Thriller de memória e confiança.', 'Intrínseca', '2011', '1ª edição', 'Português', '384', '360g', '16+'),
(91, 'A Mulher na Janela', 'A.J. Finn', 'R$ 42,90', 'Suspense', 0, '91.jpg', 'Anna Fox não sai de casa há meses e espia os vizinhos pela janela. Um dia vê algo que não deveria. Ou viu? Thriller hitchcockiano irresistível.', 'Arqueiro', '2018', '1ª edição', 'Português', '448', '420g', '16+'),
(92, 'Os Homens que Não Amavam as Mulheres', 'Stieg Larsson', 'R$ 45,90', 'Suspense', 0, '92.jpg', 'Mikael Blomkvist investiga o desaparecimento de uma herdeira há 40 anos com a ajuda da hacker Lisbeth Salander. Início da trilogia Millennium.', 'Companhia das Letras', '2005', '1ª edição', 'Português', '672', '630g', '18+'),
(93, 'O Colecionador', 'John Fowles', 'R$ 37,90', 'Suspense', 0, '93.jpg', 'Um homem sequestra uma jovem fotógrafa numa obsessão perturbadora. Narrado pelos dois lados, é um estudo brilhante e perturbador de psicologia doentia.', 'Geração Editorial', '1963', '2ª edição', 'Português', '320', '305g', '18+'),
(94, 'E Não Sobrou Nenhum', 'Agatha Christie', 'R$ 36,90', 'Suspense', 0, '94.jpg', 'Dez pessoas são convidadas para uma ilha isolada. Uma a uma, começam a morrer. O maior mistério policial de Agatha Christie - e da história.', 'Harper Collins', '1939', 'Edição especial', 'Português', '240', '230g', '14+'),
(95, 'O Homem de Giz', 'C.J. Tudor', 'R$ 40,90', 'Suspense', 0, '95.jpg', 'Em 1986, um grupo de crianças é ligado por um homem de giz. Décadas depois, alguém as está encontrando uma a uma. Thriller de atmosfera sufocante.', 'Intrínseca', '2017', '1ª edição', 'Português', '368', '350g', '18+'),
(96, 'O Casal Que Mora Ao Lado', 'Shari Lapena', 'R$ 41,90', 'Suspense', 0, '96.jpg', 'Um bebê desaparece na noite em que os vizinhos jantam pela primeira vez. Todos têm segredos. Ninguém está sendo completamente honesto.', 'Arqueiro', '2016', '1ª edição', 'Português', '336', '320g', '16+'),
(97, 'A Corrente', 'Adrian McKinty', 'R$ 43,90', 'Suspense', 0, '97.jpg', 'Uma família recebe um telefonema: raptem alguém ou seu filho morre. Um thriller de sequestro com regras que ninguém pode quebrar - ou podem?', 'Arqueiro', '2017', '1ª edição', 'Português', '352', '335g', '16+'),
(98, 'Flores Partidas', 'Karin Slaughter', 'R$ 39,90', 'Suspense', 0, '98.jpg', 'Quando uma adolescente desaparece, seu passado e o de sua cidade são escancarados. Karin Slaughter cria personagens complexos num thriller de tirar o fôlego.', 'Arqueiro', '2001', '1ª edição', 'Português', '400', '380g', '18+'),
(99, 'Jantar Secreto', 'Raphael Montes', 'R$ 38,90', 'Suspense', 0, '99.jpg', 'Um jovem obcecado por uma mulher recorre a métodos cada vez mais sombrios para tê-la. O thriller brasileiro mais perturbador da última década.', 'Companhia das Letras', '2013', '3ª edição', 'Português', '256', '245g', '18+'),
(100, 'Box Trilogia O Senhor dos Anéis', 'J.R.R. Tolkien', 'R$ 185,00', 'Fantasia Medieval', 1, '100.jpg', 'Box com os três volumes da trilogia épica de Tolkien - A Sociedade do Anel, As Duas Torres e O Retorno do Rei - a maior saga de fantasia de todos os tempos.', 'HarperCollins Brasil', '1954', 'Edição box especial', 'Português', '1296', '1500g', '12+'),
(101, 'O Hobbit', 'J.R.R. Tolkien', 'R$ 49,90', 'Fantasia Medieval', 0, '101.jpg', 'O hobbit Bilbo Bolseiro é arrastado por Gandalf em uma aventura com anões e um dragão. A história que antecede O Senhor dos Anéis.', 'HarperCollins Brasil', '1937', 'Edição especial ilustrada', 'Português', '336', '320g', '10+'),
(102, 'Box As Crônicas de Nárnia', 'C.S. Lewis', 'R$ 295,00', 'Fantasia Medieval', 0, '102.jpg', 'Box com os sete volumes das Crônicas de Nárnia, o mundo mágico acessado por um guarda-roupa, numa saga de aventura, fé e imaginação.', 'WMF Martins Fontes', '1950', 'Edição box comemorativa', 'Português', '1024', '1200g', '10+'),
(103, 'Eragon', 'Christopher Paolini', 'R$ 47,90', 'Fantasia Medieval', 0, '103.jpg', 'Eragon descobre um ovo de dragão e sua vida muda para sempre. Uma épica aventura escrita por um adolescente prodígio que conquistou o mundo.', 'Rocco', '2003', '1ª edição', 'Português', '560', '530g', '12+'),
(104, 'A Canção do Sangue', 'Anthony Ryan', 'R$ 43,90', 'Fantasia Medieval', 0, '104.jpg', 'Vaelin Al Sorna foi entregue à Ordem ainda criança e se torna um guerreiro lendário. Uma fantasia épica de guerra, fé e destino inevitável.', 'Galera Record', '2011', '1ª edição', 'Português', '560', '530g', '16+'),
(105, 'A Espada do Verão', 'Rick Riordan', 'R$ 44,90', 'Fantasia Medieval', 0, '105.jpg', 'Magnus Chase, primo de Percy Jackson, descobre ser filho de Frey e enfrenta os mitos nórdicos no mais novo spin-off de Rick Riordan.', 'Intrínseca', '2015', '1ª edição', 'Português', '512', '485g', '12+'),
(106, 'O Nome do Vento', 'Patrick Rothfuss', 'R$ 52,90', 'Fantasia Medieval', 1, '106.jpg', 'Kvothe narra sua própria lenda: como se tornou o mago mais temido do mundo. Uma obra-prima da fantasia moderna, rica em magia, música e tragédia.', 'Galera Record', '2007', '1ª edição', 'Português', '896', '840g', '16+'),
(107, 'A Guerra dos Tronos', 'George R.R. Martin', 'R$ 59,90', 'Fantasia Medieval', 0, '107.jpg', 'As casas nobres de Westeros travam uma guerra de tronos enquanto uma ameaça sobrenatural se aproxima do norte. Base da série Game of Thrones.', 'Leya', '1996', 'Edição especial', 'Português', '832', '780g', '18+'),
(108, 'Mistborn - O Império Final', 'Brandon Sanderson', 'R$ 54,90', 'Fantasia Medieval', 0, '108.jpg', 'Numa sociedade onde o metal queima no ar e cinzas cobrem o céu, uma ladrã lidera uma rebelião contra o Senhor Supremo imortal. Sanderson no auge.', 'Galera Record', '2006', '1ª edição', 'Português', '672', '640g', '16+'),
(109, 'O Caminho dos Reis', 'Brandon Sanderson', 'R$ 64,90', 'Fantasia Medieval', 0, '109.jpg', 'Kaladin, escravo e soldado, descende ao abismo e sobe como algo muito maior. Início da épica Stormlight Archive de Brandon Sanderson.', 'Galera Record', '2010', '1ª edição', 'Português', '1008', '940g', '16+'),
(110, 'A Lâmina Assassina', 'Sarah J. Maas', 'R$ 54,90', 'Fantasia Medieval', 0, '110.jpg', 'Celaena Sardothien, a assassina mais temida do reino, enfrenta seus maiores inimigos em uma fantasia medieval de ritmo acelerado e reviravoltas.', 'Galera Record', '2014', '1ª edição', 'Português', '448', '420g', '16+'),
(111, 'Conan, o Bárbaro', 'Robert E. Howard', 'R$ 44,90', 'Fantasia Medieval', 0, '111.jpg', 'Conan o Cimério percorre terras sombrias em busca de aventura e glória. As histórias originais de Robert E. Howard que definiram o herói bárbaro.', 'Devir', '1932', 'Edição completa', 'Português', '400', '380g', '16+'),
(112, 'A Roda do Tempo - O Olho do Mundo', 'Robert Jordan', 'R$ 59,90', 'Fantasia Medieval', 0, '112.jpg', 'Rand al\'Thor descobre ser o Dragon Renascido e deve aceitar seu destino para salvar o mundo. Início da série épica de 14 volumes de Robert Jordan.', 'Galera Record', '1990', '1ª edição revisada', 'Português', '832', '780g', '14+'),
(113, 'O Feiticeiro de Terramar', 'Ursula K. Le Guin', 'R$ 44,90', 'Fantasia Medieval', 0, '113.jpg', 'Ged estuda magia na ilha de Roke e libera acidentalmente uma sombra que o perseguirá pelo mundo. Fantasia filosófica e poética de Ursula K. Le Guin.', 'Aleph', '1968', 'Edição especial', 'Português', '240', '230g', '12+'),
(114, 'As Crônicas de Artur - O Rei do Inverno', 'Bernard Cornwell', 'R$ 47,90', 'Fantasia Medieval', 0, '114.jpg', 'A saga do Rei Artur narrada por Derfel Cadarn, guerreiro que viveu a lenda. Cornwell combina história e mito com maestria épica única.', 'Galera Record', '1995', '1ª edição', 'Português', '480', '450g', '16+'),
(115, 'Percy Jackson e o Ladrão de Raios', 'Rick Riordan', 'R$ 44,90', 'Fantasia Urbana', 1, '115.jpg', 'Percy Jackson descobre ser filho de Poseidon e é acusado de roubar o raio de Zeus. Uma aventura olímpica moderna, divertida e cheia de mitologia.', 'Intrínseca', '2005', 'Edição especial', 'Português', '400', '380g', '10+'),
(116, 'Box Harry Potter', 'J.K. Rowling', 'R$ 54,90', 'Fantasia Urbana', 1, '116.jpg', 'Box com os 7 volumes da saga de Harry Potter, o bruxo que enfrenta Lord Voldemort. A série infanto-juvenil mais vendida de todos os tempos.', 'Rocco', '1997', 'Box edição especial', 'Português', '4224', '4800g', '10+'),
(117, 'Deuses Americanos', 'Neil Gaiman', 'R$ 49,90', 'Fantasia Urbana', 0, '117.jpg', 'Shadow sai da prisão e começa a trabalhar para o misterioso Wednesday, descobrindo que os velhos deuses americanos travam guerra contra os novos.', 'Intrínseca', '2001', 'Edição definitiva', 'Português', '592', '560g', '16+'),
(118, 'Anjos e Demônios', 'Dan Brown', 'R$ 39,90', 'Fantasia Urbana', 0, '118.jpg', 'Robert Langdon investiga um assassinato no Vaticano e descobre o paradoxo ciência vs. fé. Prequel de O Código Da Vinci, de Dan Brown.', 'Sextante', '2000', '2ª edição', 'Português', '640', '600g', '16+'),
(119, 'Coraline', 'Neil Gaiman', 'R$ 38,90', 'Fantasia Urbana', 0, '119.jpg', 'Coraline encontra uma porta secreta que leva a um mundo perfeito - mas a mãe-outra tem botões no lugar dos olhos. Fantasia perturbadora de Neil Gaiman.', 'HarperCollins Brasil', '2002', 'Edição ilustrada', 'Português', '192', '185g', '12+'),
(120, 'A Vida Invisível de Addie LaRue', 'V.E. Schwab', 'R$ 52,90', 'Fantasia Urbana', 1, '120.jpg', 'Addie LaRue faz um pacto com o diabo: viverá para sempre, mas ninguém a lembrará. Após 300 anos, um jovem a reconhece. Uma fábula de amor e liberdade.', 'Galera Record', '2020', '1ª edição', 'Português', '448', '420g', '16+'),
(121, 'Nona Casa', 'Leigh Bardugo', 'R$ 49,90', 'Fantasia Urbana', 0, '121.jpg', 'Alex Stern entra em Yale com um dom especial: ver fantasmas. É recrutada para vigiar as sociedades secretas ocultas do campus. Fantasia sombria e feminista.', 'Galera Record', '2019', '1ª edição', 'Português', '480', '450g', '18+'),
(122, 'A Casa no Mar Gerúleo', 'TJ Klune', 'R$ 46,90', 'Fantasia Urbana', 0, '122.jpg', 'Um assistente social descobre que a casa no mar que administra é habitada por personagens de um livro infantil. Uma fantasia reconfortante sobre família.', 'Arqueiro', '2020', '1ª edição', 'Português', '368', '350g', '14+'),
(123, 'Os Sete Maridos de Evelyn Hugo', 'Taylor Jenkins Reid', 'R$ 49,90', 'Fantasia Urbana', 0, 't.jpg', 'Monique Grant entrevista a lendária atriz Evelyn Hugo, que finalmente vai contar seus sete casamentos e os segredos que guardou por décadas.', 'Intrínseca', '2017', '1ª edição', 'Português', '384', '360g', '16+'),
(124, 'Dom Casmurro', 'Machado de Assis', 'R$ 28,90', 'Clássicos', 0, '123.jpg', 'Bentinho, o Dom Casmurro, suspeita de traição da esposa Capitu. O maior romance do realismo brasileiro, ainda hoje debate gerações sobre culpa e ciúme.', 'Penguin Companhia', '1899', 'Edição especial comentada', 'Português', '272', '260g', '14+'),
(125, 'Memórias Póstumas de Brás Cubas', 'Machado de Assis', 'R$ 30,90', 'Clássicos', 0, '124.jpg', 'Brás Cubas narra sua vida depois de morto, com ironia única. A obra-prima que inaugurou o realismo no Brasil com humor e filosofia.', 'Penguin Companhia', '1881', 'Edição especial', 'Português', '288', '275g', '14+'),
(126, 'Os Miseráveis', 'Victor Hugo', 'R$ 54,90', 'Clássicos', 1, '125.jpg', 'Jean Valjean foge de uma perseguição implacável numa Paris miserável. O monumento da literatura francesa sobre justiça, redenção e o poder do amor.', 'Cosac Naify', '1862', 'Edição integral', 'Português', '1488', '1400g', '14+'),
(127, 'Crime e Castigo', 'Fiódor Dostoiévski', 'R$ 49,90', 'Clássicos', 0, '126.jpg', 'Raskólnikov acredita que pode matar sem culpa - mas o crime transforma sua mente. O maior romance psicológico da literatura, segundo muitos críticos.', 'Penguin Companhia', '1866', 'Tradução nova', 'Português', '608', '575g', '16+'),
(128, 'O Grande Gatsby', 'F. Scott Fitzgerald', 'R$ 34,90', 'Clássicos', 0, '127.jpg', 'Jay Gatsby joga festas extravagantes esperando reencontrar Daisy Buchanan. Uma fábula sobre o sonho americano, a riqueza e o amor impossível.', 'Penguin Companhia', '1925', 'Edição especial', 'Português', '208', '200g', '14+'),
(129, 'Moby Dick', 'Herman Melville', 'R$ 44,90', 'Clássicos', 0, '128.jpg', 'A caçada épica do capitão Ahab à baleia branca Moby Dick. Uma meditação sobre obsessão, natureza e o sentido da existência na imensidão do mar.', 'Penguin Companhia', '1851', 'Edição ilustrada', 'Português', '720', '680g', '16+'),
(130, 'Drácula', 'Bram Stoker', 'R$ 36,90', 'Clássicos', 0, '129.png', 'Jonathan Harker viaja para a Transilvânia e encontra o Conde Drácula. O romance epistolar que criou o mito do vampiro moderno.', 'Penguin Companhia', '1897', 'Edição ilustrada', 'Português', '448', '420g', '14+'),
(131, 'Frankenstein', 'Mary Shelley', 'R$ 32,90', 'Clássicos', 0, '129.jpg', 'O cientista Victor Frankenstein cria vida a partir de cadáveres e foge horrorizado de sua criação. O primeiro romance de ficção científica da história.', 'Penguin Companhia', '1818', 'Edição especial', 'Português', '240', '230g', '14+'),
(132, 'Orgulho e Preconceito', 'Jane Austen', 'R$ 34,90', 'Clássicos', 0, '1.png', 'A jovem Elizabeth Bennet navega questões de casamento, moralidade e felicidade na Inglaterra do século XIX, numa edição clássica para a coleção.', 'Martin Claret', '1813', 'Edição de bolso', 'Português', '416', '390g', '14+'),
(133, 'O Retrato de Dorian Gray', 'Oscar Wilde', 'R$ 34,90', 'Clássicos', 0, '130.jpg', 'O belo Dorian Gray permanece jovem enquanto seu retrato envelhece e registra cada pecado. Meditação wilde sobre beleza, moral e corrupção da alma.', 'Penguin Companhia', '1890', 'Edição especial', 'Português', '272', '260g', '14+'),
(134, 'Triste Fim de Policarpo Quaresma', 'Lima Barreto', 'R$ 29,90', 'Clássicos', 0, '131.jpg', 'Policarpo Quaresma é um patriota idealista que vai ao encontro de um Brasil que não existe. Sátira brilhante e melancólica de Lima Barreto.', 'Penguin Companhia', '1915', 'Edição comentada', 'Português', '240', '230g', '14+'),
(135, 'Cem Anos de Solidão', 'Gabriel García Márquez', 'R$ 52,90', 'Clássicos', 1, '132.jpg', 'A saga da família Buendía ao longo de sete gerações em Macondo. O romance do Realismo Mágico por excelência e a obra mais importante de García Márquez.', 'Record', '1967', 'Edição comemorativa', 'Português', '448', '420g', '16+'),
(136, 'O Cortiço', 'Aluísio Azevedo', 'R$ 27,90', 'Clássicos', 0, '133.jpg', 'No cortiço carioca, trabalhadores e imigrantes vivem o Brasil da escravidão e da miséria. Naturalismo brasileiro na sua expressão máxima.', 'Ática', '1890', 'Edição especial', 'Português', '288', '275g', '14+'),
(137, 'Jane Eyre', 'Charlotte Brontë', 'R$ 38,90', 'Clássicos', 0, '134.jpg', 'Jane Eyre cresce como órfã, torna-se governanta e se apaixona pelo misterioso Rochester. Um dos maiores romances feministas da literatura vitoriana.', 'Penguin Companhia', '1847', 'Tradução nova', 'Português', '624', '590g', '14+'),
(138, 'O Morro dos Ventos Uivantes', 'Emily Brontë', 'R$ 36,90', 'Clássicos', 0, '7.jpg', 'Heathcliff e Catherine no clássico amor-obsessão dos páramos ingleses. Edição revisada com notas e introdução crítica.', 'Penguin Companhia', '1847', 'Edição revisada', 'Português', '384', '365g', '16+'),
(139, 'Grandes Esperanças', 'Charles Dickens', 'R$ 42,90', 'Clássicos', 0, '135.jpg', 'O órfão Pip sonha em ser cavalheiro numa saga sobre ambição, gratidão e identidade na Inglaterra vitoriana de Charles Dickens.', 'Penguin Companhia', '1861', 'Edição especial', 'Português', '624', '590g', '14+'),
(140, 'Anna Kariênina', 'Lev Tolstói', 'R$ 54,90', 'Clássicos', 0, '136.jpg', 'Anna Kariênina abandona o marido pelo conde Vronski e paga um preço devastador. Tolstói sobre amor, sociedade e a impossibilidade de ser livre.', 'Penguin Companhia', '1878', 'Tradução nova', 'Português', '896', '840g', '16+'),
(141, 'It: A Coisa', 'Stephen King', 'R$ 59,90', 'Horror', 1, '137.jpg', 'Em Derry, um ser maligno que se disfarça de palhaço desperta a cada 27 anos para se alimentar de crianças. O maior livro de Stephen King.', 'Suma de Letras', '1986', 'Edição especial', 'Português', '1376', '1280g', '18+'),
(142, 'O Iluminado', 'Stephen King', 'R$ 49,90', 'Horror', 0, '138.jpg', 'A família Torrance vai trabalhar num hotel isolado no Colorado durante o inverno. O hotel tem seus próprios planos para o pequeno Danny.', 'Suma de Letras', '1977', 'Edição especial', 'Português', '512', '485g', '18+'),
(143, 'Drácula', 'Bram Stoker', 'R$ 36,90', 'Horror', 0, '129.png', 'O Conde Drácula sai da Transilvânia para Londres. O clássico do horror gótico em edição especial para a coleção Horror.', 'Darkside Books', '1897', 'Edição ilustrada', 'Português', '480', '450g', '14+'),
(144, 'Frankenstein', 'Mary Shelley', 'R$ 32,90', 'Horror', 0, '129.jpg', 'Victor Frankenstein e sua criatura trágica. Edição especial para a coleção Horror com introdução e ensaio crítico.', 'Darkside Books', '1818', 'Edição ilustrada', 'Português', '256', '245g', '14+'),
(145, 'O Exorcista', 'William Peter Blatty', 'R$ 42,90', 'Horror', 0, '139.jpg', 'O padre Damien Karras investiga a possessão da jovem Regan MacNeil. O romance de terror psicológico e religioso mais aterrorizante já escrito.', 'Record', '1971', '2ª edição', 'Português', '336', '320g', '18+'),
(146, 'A Assombração da Casa da Colina', 'Shirley Jackson', 'R$ 39,90', 'Horror', 0, '140.jpg', 'Shirley Jackson escreve o romance mais assustador da história da literatura de casas mal-assombradas. Atmosfera de horror psicológico absoluto.', 'Darkside Books', '1959', 'Edição especial', 'Português', '256', '245g', '16+'),
(147, 'Hell House', 'Richard Matheson', 'R$ 38,90', 'Horror', 0, '141.jpg', 'Um grupo de investigadores do paranormal é confinado na Belasco House, a casa mais mal-assombrada do mundo. Terror intenso e cerebral de Richard Matheson.', 'Darkside Books', '1971', '1ª edição brasileira', 'Português', '256', '245g', '18+'),
(148, 'Coraline', 'Neil Gaiman', 'R$ 38,90', 'Horror', 0, 'C.jpg', 'Coraline encontra um mundo paralelo encantador com uma mãe-outra de botões. Uma história de horror perturbadora para todas as idades.', 'HarperCollins Brasil', '2002', 'Edição ilustrada', 'Português', '192', '185g', '12+'),
(149, 'Caixa de Pássaros', 'Josh Malerman', 'R$ 38,90', 'Horror', 0, '142.png', 'Quando criaturas desconhecidas chegam, ver significa morrer. Malorie navega às cegas com dois bebês em busca de um abrigo. Horror pós-apocalíptico.', 'Darkside Books', '2014', '1ª edição', 'Português', '288', '275g', '16+'),
(150, 'O Vilarejo', 'Raphael Montes', 'R$ 36,90', 'Horror', 0, '143.jpg', 'Um homem chega a um vilarejo isolado no interior do Brasil onde estranhos segredos emergem. Horror brasileiro de Raphael Montes.', 'Companhia das Letras', '2019', '1ª edição', 'Português', '256', '245g', '18+'),
(151, 'O Cemitério', 'Stephen King', 'R$ 47,90', 'Horror', 0, '144.jpg', 'Louis Creed descobre um cemitério com poderes sombrios. O que volta de lá não é o mesmo que partiu. Stephen King sobre o luto e o preço da ressurreição.', 'Suma de Letras', '1983', 'Edição especial', 'Português', '496', '470g', '18+'),
(152, 'Amityville', 'Jay Anson', 'R$ 39,90', 'Horror', 0, '145.jpg', 'A família Lutz muda para uma casa em Amityville onde houve uma chacina. 28 dias depois, fogem aterrorizados. Baseado em fatos reais.', 'Record', '1977', '2ª edição', 'Português', '352', '335g', '16+'),
(153, 'O Chamado de Cthulhu e Outros Contos', 'H.P. Lovecraft', 'R$ 42,90', 'Horror', 0, '146.jpg', 'Lovecraft mergulha nas profundezas do horror cósmico com seu ser mais icônico - Cthulhu - e outros monstros inimagináveis que esperam no escuro.', 'Darkside Books', '1926', 'Edição especial', 'Português', '320', '305g', '16+'),
(154, 'Misery: Louca Obsessão', 'Stephen King', 'R$ 46,90', 'Horror', 0, '147.jpg', 'A escritora Annie Wilkes resgata o romancista Paul Sheldon após um acidente e o mantém cativo. Stephen King em seu thriller psicológico mais claustrofóbico.', 'Suma de Letras', '1987', 'Edição especial', 'Português', '432', '410g', '18+'),
(155, 'O Homem de Giz', 'C.J. Tudor', 'R$ 40,90', 'Horror', 0, '95.jpg', 'Em 1986, um boneco de giz une um grupo de crianças. Décadas depois, alguém as está encontrando. Horror de C.J. Tudor na coleção Horror.', 'Intrínseca', '2017', '1ª edição', 'Português', '368', '350g', '18+'),
(156, 'A Autoestrada da Morte', 'Stephen King', 'R$ 44,90', 'Horror', 0, '149.jpg', 'Num futuro distópico, a autoestrada interestadual se torna um pesadelo após uma bolha de neblina mortal cobrir tudo. Stephen King, obra de estreia.', 'Suma de Letras', '1969', 'Edição especial', 'Português', '352', '335g', '18+'),
(157, '1984', 'George Orwell', 'R$ 38,90', 'Distopia', 0, '70.png', 'Na Inglaterra totalitária de 1984, o Big Brother vigia tudo e todos. Uma das obras mais proféticas e importantes da literatura do século XX.', 'Companhia das Letras', '1949', 'Edição especial', 'Português', '416', '390g', '16+'),
(158, 'Admirável Mundo Novo', 'Aldous Huxley', 'R$ 39,90', 'Distopia', 0, '71.jpg', 'Huxley imagina um futuro de prazer forçado e condicionamento social. A distopia irmã de 1984, igualmente profética sobre o controle pelo consumo.', 'Globo', '1932', 'Edição especial', 'Português', '336', '320g', '16+'),
(159, 'Jogos Vorazes', 'Suzanne Collins', 'R$ 42,90', 'Distopia', 0, '75.jpg', 'Katniss Everdeen luta pela sobrevivência em jogos mortais televisionados. O símbolo da resistência distópica na literatura jovem adulta.', 'Rocco', '2008', 'Edição especial', 'Português', '400', '380g', '12+'),
(160, 'Divergente', 'Veronica Roth', 'R$ 42,90', 'Distopia', 0, '150.jpg', 'Beatrice Prior vive numa sociedade dividida em facções e descobre ser Divergente. Uma distopia jovem sobre identidade, escolha e rebeldia.', 'Harper Collins', '2011', '1ª edição', 'Português', '496', '470g', '14+'),
(161, 'Fahrenheit 451', 'Ray Bradbury', 'R$ 36,90', 'Distopia', 0, '76.jpg', 'Guy Montag é um bombeiro que queima livros, mas começa a questioná-lo. Bradbury sobre censura, tecnologia e o que significa ser humano.', 'Globo', '1953', 'Edição especial', 'Português', '256', '245g', '14+'),
(162, 'A Seleção', 'Kiera Cass', 'R$ 40,90', 'Distopia', 0, '25.jpg', 'America Singer não quer participar da Seleção de esposas do príncipe - mas sua vida é transformada de formas que ela nunca esperou.', 'Galera Record', '2012', 'Edição especial', 'Português', '336', '320g', '14+'),
(163, 'O Conto da Aia', 'Margaret Atwood', 'R$ 44,90', 'Distopia', 1, '151.jpg', 'Offred vive como serva reprodutora numa teocracia totalitária. Atwood escreve o livro feminista mais importante e aterrorizante já publicado.', 'Rocco', '1985', 'Edição especial', 'Português', '368', '350g', '16+'),
(164, 'Laranja Mecânica', 'Anthony Burgess', 'R$ 38,90', 'Distopia', 0, '152.jpg', 'Alex é um jovem violento que passa por uma cura comportamental governamental. Burgess questiona o livre-arbítrio e o preço da violência.', 'Aleph', '1962', 'Edição integral', 'Português', '256', '245g', '18+');
INSERT INTO `livros` (`id`, `titulo`, `autor`, `preco`, `categoria`, `destaque`, `imagem`, `sinopse`, `editora`, `publicacao`, `edicao`, `idioma`, `paginas`, `peso`, `idade`) VALUES
(165, 'Ensaio sobre a Cegueira', 'José Saramago', 'R$ 42,90', 'Distopia', 0, '153.jpg', 'Uma epidemia de cegueira se espalha. Os afetados são isolados num manicômio abandonado. Saramago sobre a barbárie que habita a civilização.', 'Companhia das Letras', '1995', 'Edição especial', 'Português', '352', '335g', '18+'),
(166, 'Estação Onze', 'Emily St. John Mandel', 'R$ 44,90', 'Distopia', 1, '154.jpg', '20 anos depois de uma pandemia que eliminou a maioria da humanidade, sobreviventes na neve tentam reconstruir uma vida com os fragmentos do que foi.', 'Biblioteca Azul', '2014', '1ª edição', 'Português', '336', '320g', '16+'),
(167, 'A Estrada', 'Cormac McCarthy', 'R$ 42,90', 'Distopia', 0, '155.jpg', 'Um homem e seu filho percorrem uma América devastada em busca do sul. Cormac McCarthy sobre amor paternal e a persistência humana no fim do mundo.', 'Alfaguara', '2006', '1ª edição', 'Português', '336', '320g', '16+'),
(168, 'Flores para Algernon', 'Daniel Keyes', 'R$ 39,90', 'Distopia', 0, '156.jpg', 'Charlie Gordon tem QI baixo e é submetido a uma cirurgia experimental que o torna um gênio - mas a transformação tem um custo devastador.', 'Aleph', '1966', '1ª edição brasileira', 'Português', '320', '305g', '14+'),
(169, 'Nós', 'Zamiátin', 'R$ 37,90', 'Distopia', 0, '157.jpg', 'No Estado Único, as pessoas vivem como números. D-503 encontra I-330 e questiona a ordem perfeita. A distopia russa que inspirou Orwell.', 'Aleph', '1924', '1ª edição brasileira', 'Português', '240', '230g', '16+'),
(170, 'Metrópolis', 'Thea von Harbou', 'R$ 36,90', 'Distopia', 0, '158.jpg', 'Maria vive em Metrópolis, dividida entre trabalhadores subterrâneos e elite aérea. A novela que originou o filme clássico de Fritz Lang.', 'Devir', '1925', '1ª edição brasileira', 'Português', '224', '215g', '14+'),
(171, 'A Metamorfose', 'Franz Kafka', 'R$ 24,90', 'Novela', 0, '159.jpg', 'Gregor Samsa acorda transformado em inseto. Uma das metáforas mais poderosas da literatura sobre alienação, família e a condição humana.', 'Companhia das Letras', '1915', 'Edição especial', 'Português', '128', '140g', '14+'),
(172, 'O Estrangeiro', 'Albert Camus', 'R$ 28,90', 'Novela', 0, '160.jpg', 'Meursault mata um árabe sob o sol de Argel e enfrenta o julgamento mais filosófico da história da literatura. Camus sobre o absurdo da existência.', 'Record', '1942', 'Edição especial', 'Português', '160', '170g', '16+'),
(173, 'A Morte de Ivan Ilitch', 'Lev Tolstói', 'R$ 26,90', 'Novela', 0, '161.jpg', 'Ivan Ilitch está morrendo e percebe que viveu de forma falsa. Tolstói em sua meditação mais devastadora sobre a morte e o que realmente importa.', 'Penguin Companhia', '1886', 'Edição especial', 'Português', '128', '140g', '14+'),
(174, 'Noites Brancas', 'Fiódor Dostoiévski', 'R$ 25,90', 'Novela', 0, '162.png', 'Um jovem sonhador encontra nas noites brancas de São Petersburgo uma jovem que espera o amado. Dostoiévski sobre amor, ilusão e o poder dos sonhos.', 'Penguin Companhia', '1848', 'Edição especial', 'Português', '96', '110g', '14+'),
(175, 'O Velho e o Mar', 'Ernest Hemingway', 'R$ 28,90', 'Novela', 1, '163.jpg', 'O velho Santiago luta sozinho com um enorme marlim no Golfo do México. A novela mais famosa de Hemingway sobre resistência, derrota e dignidade.', 'Bertrand Brasil', '1952', 'Edição especial', 'Português', '144', '155g', '14+'),
(176, 'Bartleby, o Escriturário', 'Herman Melville', 'R$ 22,90', 'Novela', 0, '164.jpg', 'O escrivão Bartleby preferiria não fazer nada. Uma das novelas mais enigmáticas da literatura americana sobre passividade e desumanização do trabalho.', 'Penguin Companhia', '1853', 'Edição especial', 'Português', '96', '110g', '14+'),
(177, 'A Revolução dos Bichos', 'George Orwell', 'R$ 26,90', 'Novela', 0, '00.jpg', 'Os animais da fazenda expulsam os humanos e criam seu próprio governo igualitário - que aos poucos se torna indistinguível da tirania anterior.', 'Penguin Companhia', '1945', 'Edição especial', 'Português', '128', '140g', '12+'),
(178, 'O Alienista', 'Machado de Assis', 'R$ 24,90', 'Novela', 0, '165.jpg', 'O alienista Simão Bacamarte decide internar todos os loucos de Itaguaí - e depois todos os sãos. Machado de Assis em sua sátira mais brilhante.', 'Penguin Companhia', '1882', 'Edição comentada', 'Português', '96', '110g', '14+'),
(179, 'Coração das Trevas', 'Joseph Conrad', 'R$ 27,90', 'Novela', 0, '166.jpg', 'Marlow narra sua viagem pelo Congo e a busca por Kurtz, o homem que foi além dos limites da civilização. Conrad sobre colonialismo e a escuridão interior.', 'Penguin Companhia', '1899', 'Edição especial', 'Português', '128', '140g', '16+'),
(180, 'A Hora da Estrela', 'Clarice Lispector', 'R$ 28,90', 'Novela', 0, '167.jpg', 'Macabéa é a nordestina invisível no Rio de Janeiro. Clarice Lispector em seu último romance, sobre existência, beleza e o direito de ser.', 'Rocco', '1977', 'Edição especial', 'Português', '112', '125g', '16+'),
(181, 'O Perfeccionista', 'Rudolf Chelminski', 'R$ 26,90', 'Novela', 0, '168.jpg', 'A história do chef Bernard Loiseau, o perfeccionista que levou a gastronomia francesa ao absoluto e pagou um preço impossível pela perfeição.', 'Record', '2005', '1ª edição', 'Português', '288', '275g', '16+'),
(182, 'O Médico e o Monstro', 'Robert Louis Stevenson', 'R$ 24,90', 'Novela', 0, '169.jpg', 'O Dr. Jekyll bebe uma poção e libera Hyde, seu lado sombrio. Stevenson escreve o clássico sobre a dualidade da natureza humana.', 'Penguin Companhia', '1886', 'Edição especial', 'Português', '128', '140g', '14+'),
(183, 'O Fantasma da Ópera', 'Gaston Leroux', 'R$ 22,90', 'Novela', 0, '170.jpg', 'O Fantasma mora nas catacumbas da Ópera de Paris e é apaixonado pela soprano Christine. Um romance gótico de obsessão, arte e amor impossível.', 'Martin Claret', '1910', '2ª edição', 'Português', '352', '335g', '14+');

CREATE TABLE `usuarios` (
  `id` int(11) NOT NULL,
  `nome` varchar(150) NOT NULL,
  `cpf` varchar(14) NOT NULL,
  `endereco` varchar(200) NOT NULL,
  `bairro` varchar(100) NOT NULL,
  `cidade` varchar(100) NOT NULL,
  `estado` char(2) NOT NULL,
  `cep` varchar(9) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `vendas` (
  `id` int(11) NOT NULL,
  `numero_venda` varchar(30) NOT NULL,
  `login` varchar(60) NOT NULL,
  `nome` varchar(150) DEFAULT NULL,
  `data_hora` datetime DEFAULT NULL,
  `forma_pagamento` varchar(50) DEFAULT NULL,
  `total` decimal(10,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `venda_itens` (
  `id` int(11) NOT NULL,
  `venda_id` int(11) NOT NULL,
  `titulo` varchar(200) DEFAULT NULL,
  `autor` varchar(120) DEFAULT NULL,
  `preco` varchar(20) DEFAULT NULL,
  `quantidade` int(11) DEFAULT 1,
  `categoria` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `acesso`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `login` (`login`);

ALTER TABLE `livros`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `usuarios`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `cpf` (`cpf`);

ALTER TABLE `vendas`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `numero_venda` (`numero_venda`);

ALTER TABLE `venda_itens`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `acesso`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

ALTER TABLE `livros`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=184;

ALTER TABLE `usuarios`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

ALTER TABLE `vendas`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

ALTER TABLE `venda_itens`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;
COMMIT;